#!/bin/bash
export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_05/bin:$PATH
export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk1.8.0_05"
nohup $OPENSHIFT_REPO_DIR/target/universal/stage/bin/my_project -J-Xms128M -J-Xmx500M -Dhttp.address=$OPENSHIFT_DIY_IP -Dhttp.port=8080 -Dpidfile.path=$OPENSHIFT_REPO_DIR/misc/pid.pid &
